import type { EventModel } from "./types";

export const mockEvents: EventModel[] = [
  {
    id: "evt-1",
    name: "Sarah & James Wedding",
    status: "in_progress",
    type: "wedding",
    pinned: true,
    date: "2026-09-12T17:00:00Z",
    updatedAt: "2026-06-09T14:00:00Z",
    venue: {
      name: "The Glasshouse at Kew",
      address: "Kew Gardens, Richmond TW9 3AB",
      confirmed: true,
    },
    catering: {
      name: "Bloom & Wild Catering",
      menu: "Seasonal tasting menu, 5 courses",
      confirmed: true,
    },
    attendees: { count: 120, confirmed: 96 },
    schedule: [
      { time: "15:00", title: "Guest arrival & welcome drinks" },
      { time: "16:00", title: "Ceremony" },
      { time: "17:30", title: "Cocktail hour & photos" },
      { time: "19:00", title: "Dinner service" },
      { time: "21:30", title: "First dance" },
      { time: "00:00", title: "Carriages" },
    ],
    budget: { committed: 48000, spent: 22500, total: 60000 },
    topics: ["Floral palette", "Seating chart", "Welcome bags", "Live music", "Late-night snacks"],
    vendors: [
      {
        id: "v1",
        category: "venue",
        vendorName: "The Glasshouse at Kew",
        contactName: "Eleanor Pritchard",
        phone: "+44 20 8332 5000",
        email: "events@kew.org",
        website: "https://kew.org",
        status: "booked",
        notes: "Walk-through booked for August 14.",
        statusHistory: [
          { status: "quote_requested", timestamp: "2026-02-10T10:00:00Z" },
          { status: "deposit_paid", timestamp: "2026-03-01T10:00:00Z" },
          { status: "booked", timestamp: "2026-03-05T10:00:00Z" },
        ],
      },
      {
        id: "v2",
        category: "catering",
        vendorName: "Bloom & Wild Catering",
        contactName: "Marco Rossi",
        phone: "+44 20 7946 0100",
        email: "marco@bloomwild.co",
        website: "https://bloomwild.co",
        status: "deposit_paid",
        notes: "Final menu tasting on July 22.",
        statusHistory: [
          { status: "quote_requested", timestamp: "2026-03-12T10:00:00Z" },
          { status: "deposit_paid", timestamp: "2026-04-02T10:00:00Z" },
        ],
      },
      {
        id: "v3",
        category: "flowers",
        vendorName: "Fern & Petal Studio",
        contactName: "Iris Nakamura",
        phone: "+44 7700 900123",
        email: "hello@fernpetal.com",
        status: "awaiting_confirmation",
        statusHistory: [{ status: "quote_requested", timestamp: "2026-05-01T10:00:00Z" }],
      },
      {
        id: "v4",
        category: "photography",
        vendorName: "Hugo Lane Photography",
        contactName: "Hugo Lane",
        phone: "+44 7700 900456",
        email: "hugo@hugolane.photo",
        website: "https://hugolane.photo",
        status: "booked",
        statusHistory: [{ status: "booked", timestamp: "2026-04-18T10:00:00Z" }],
      },
      {
        id: "v5",
        category: "dj",
        vendorName: "Northern Lights DJs",
        contactName: "Theo Park",
        phone: "+44 7700 900789",
        email: "bookings@northernlightsdjs.com",
        status: "quote_requested",
        statusHistory: [{ status: "quote_requested", timestamp: "2026-05-20T10:00:00Z" }],
      },
      {
        id: "v6",
        category: "cake",
        vendorName: "Honey & Co Patisserie",
        contactName: "Yotam Levi",
        phone: "+44 20 7833 1010",
        email: "orders@honeyandco.com",
        status: "deposit_paid",
        statusHistory: [{ status: "deposit_paid", timestamp: "2026-05-12T10:00:00Z" }],
      },
      {
        id: "v7",
        category: "transport",
        vendorName: "Vintage Wheels Co.",
        contactName: "Daisy Brown",
        phone: "+44 7700 900222",
        email: "hire@vintagewheels.co",
        status: "awaiting_confirmation",
        statusHistory: [{ status: "quote_requested", timestamp: "2026-05-28T10:00:00Z" }],
      },
    ],
    milestones: [
      { id: "m1", date: "2026-06-20", title: "Send save-the-dates", category: "communication", status: "done" },
      { id: "m2", date: "2026-07-22", title: "Menu tasting", category: "catering", status: "pending" },
      { id: "m3", date: "2026-08-01", title: "Final headcount due", category: "logistics", status: "pending" },
      { id: "m4", date: "2026-08-14", title: "Venue walk-through", category: "venue", status: "pending" },
      { id: "m5", date: "2026-08-30", title: "Final balance to caterer", category: "finance", status: "pending" },
    ],
  },
  {
    id: "evt-2",
    name: "Acme Q4 Launch",
    status: "planning",
    type: "launch",
    date: "2026-11-04T18:00:00Z",
    updatedAt: "2026-06-08T10:00:00Z",
    attendees: { count: 250, confirmed: 0 },
    budget: { committed: 12000, spent: 2000, total: 80000 },
    topics: ["Stage design", "Press list", "Demo flow"],
    vendors: [],
    milestones: [],
  },
  {
    id: "evt-3",
    name: "Maya turns 8 🎂",
    status: "confirmed",
    type: "birthday",
    date: "2026-07-19T14:00:00Z",
    updatedAt: "2026-06-01T10:00:00Z",
    venue: { name: "Sunny Park Pavilion", address: "Hyde Park, London", confirmed: true },
    attendees: { count: 22, confirmed: 18 },
    budget: { committed: 800, spent: 350, total: 1200 },
    vendors: [],
    milestones: [],
  },
  {
    id: "evt-4",
    name: "Annual charity gala",
    status: "draft",
    type: "social",
    date: "2027-02-15T19:00:00Z",
    updatedAt: "2026-05-30T10:00:00Z",
    vendors: [],
    milestones: [],
  },
];